Week2
choudhary-keshav/nodejs-training pull request #2
Opened 2024-04-12 05:49 UTC by choudhary-keshav

Pull Request Questionnaire

(1) Which Jira ticket(s) is this pull request for, and is the ticket now complete?

(2) Briefly describe your change.
I have pushed my week-2 assignment in this nodeJS project. In my week-2 assignment I have used middlewares & static, dynamic routes.

(3) What parts of the application are affected by your change?
Nothing

(4) How did you test your change? If relevant, which role(s) and/or customer configuration(s) did you use?
Tested my application on various edge cases and some common scenarios

2024-04-12 10:31 UTC, aditya-s-19 approved these changes

2024-04-15 05:18 UTC, shreyansh-khatri requested changes

2024-04-15 05:18 UTC, shreyansh-khatri commented on src/Week2/assignment.ts
> +//localhost:3000/
Remove these comments

2024-04-15 05:18 UTC, shreyansh-khatri commented on src/Week2/assignment.ts
> +const authenticateUser = (req: any, res: any, next: any) => {
Please specify return type

2024-04-15 05:44 UTC, RitikaGarg-ITT approved these changes

2024-04-15 07:04 UTC, shreyansh-khatri approved these changes

2024-04-15 08:53 UTC, shreegovinda approved these changes

2024-04-16 04:03 UTC, anusreesubash approved these changes

2024-04-16 04:04 UTC, merged